export type FlagCountry = {
  id: string;
  alpha2Code: string;
  displayName: string;
  assetPath: string;
  acceptedAliases: string[];
};

export const FLAG_COUNTRIES: FlagCountry[] = [
  {
    id: "af",
    alpha2Code: "AF",
    displayName: "Afghanistan",
    assetPath: "/flags/af.svg",
    acceptedAliases: ["Afghanistan", "Islamic Republic of Afghanistan"],
  },
  {
    id: "al",
    alpha2Code: "AL",
    displayName: "Albania",
    assetPath: "/flags/al.svg",
    acceptedAliases: ["Albania", "Republic of Albania"],
  },
  {
    id: "dz",
    alpha2Code: "DZ",
    displayName: "Algeria",
    assetPath: "/flags/dz.svg",
    acceptedAliases: ["Algeria", "People's Democratic Republic of Algeria"],
  },
  {
    id: "ad",
    alpha2Code: "AD",
    displayName: "Andorra",
    assetPath: "/flags/ad.svg",
    acceptedAliases: ["Andorra", "Principality of Andorra"],
  },
  {
    id: "ao",
    alpha2Code: "AO",
    displayName: "Angola",
    assetPath: "/flags/ao.svg",
    acceptedAliases: ["Angola", "Republic of Angola"],
  },
  {
    id: "ag",
    alpha2Code: "AG",
    displayName: "Antigua and Barbuda",
    assetPath: "/flags/ag.svg",
    acceptedAliases: ["Antigua and Barbuda"],
  },
  {
    id: "ar",
    alpha2Code: "AR",
    displayName: "Argentina",
    assetPath: "/flags/ar.svg",
    acceptedAliases: ["Argentina", "Argentine Republic"],
  },
  {
    id: "am",
    alpha2Code: "AM",
    displayName: "Armenia",
    assetPath: "/flags/am.svg",
    acceptedAliases: ["Armenia", "Republic of Armenia"],
  },
  {
    id: "au",
    alpha2Code: "AU",
    displayName: "Australia",
    assetPath: "/flags/au.svg",
    acceptedAliases: ["Australia", "Commonwealth of Australia"],
  },
  {
    id: "at",
    alpha2Code: "AT",
    displayName: "Austria",
    assetPath: "/flags/at.svg",
    acceptedAliases: ["Austria", "Republic of Austria"],
  },
  {
    id: "az",
    alpha2Code: "AZ",
    displayName: "Azerbaijan",
    assetPath: "/flags/az.svg",
    acceptedAliases: ["Azerbaijan", "Republic of Azerbaijan"],
  },
  {
    id: "bs",
    alpha2Code: "BS",
    displayName: "Bahamas",
    assetPath: "/flags/bs.svg",
    acceptedAliases: ["Bahamas", "Commonwealth of the Bahamas"],
  },
  {
    id: "bh",
    alpha2Code: "BH",
    displayName: "Bahrain",
    assetPath: "/flags/bh.svg",
    acceptedAliases: ["Bahrain", "Kingdom of Bahrain"],
  },
  {
    id: "bd",
    alpha2Code: "BD",
    displayName: "Bangladesh",
    assetPath: "/flags/bd.svg",
    acceptedAliases: ["Bangladesh", "People's Republic of Bangladesh"],
  },
  {
    id: "bb",
    alpha2Code: "BB",
    displayName: "Barbados",
    assetPath: "/flags/bb.svg",
    acceptedAliases: ["Barbados"],
  },
  {
    id: "by",
    alpha2Code: "BY",
    displayName: "Belarus",
    assetPath: "/flags/by.svg",
    acceptedAliases: ["Belarus", "Republic of Belarus"],
  },
  {
    id: "be",
    alpha2Code: "BE",
    displayName: "Belgium",
    assetPath: "/flags/be.svg",
    acceptedAliases: ["Belgium", "Kingdom of Belgium"],
  },
  {
    id: "bz",
    alpha2Code: "BZ",
    displayName: "Belize",
    assetPath: "/flags/bz.svg",
    acceptedAliases: ["Belize"],
  },
  {
    id: "bj",
    alpha2Code: "BJ",
    displayName: "Benin",
    assetPath: "/flags/bj.svg",
    acceptedAliases: ["Benin", "Republic of Benin"],
  },
  {
    id: "bt",
    alpha2Code: "BT",
    displayName: "Bhutan",
    assetPath: "/flags/bt.svg",
    acceptedAliases: ["Bhutan", "Kingdom of Bhutan"],
  },
  {
    id: "bo",
    alpha2Code: "BO",
    displayName: "Bolivia",
    assetPath: "/flags/bo.svg",
    acceptedAliases: ["Bolivia", "Plurinational State of Bolivia"],
  },
  {
    id: "ba",
    alpha2Code: "BA",
    displayName: "Bosnia and Herzegovina",
    assetPath: "/flags/ba.svg",
    acceptedAliases: ["Bosnia and Herzegovina"],
  },
  {
    id: "bw",
    alpha2Code: "BW",
    displayName: "Botswana",
    assetPath: "/flags/bw.svg",
    acceptedAliases: ["Botswana", "Republic of Botswana"],
  },
  {
    id: "br",
    alpha2Code: "BR",
    displayName: "Brazil",
    assetPath: "/flags/br.svg",
    acceptedAliases: ["Brazil", "Federative Republic of Brazil"],
  },
  {
    id: "bn",
    alpha2Code: "BN",
    displayName: "Brunei",
    assetPath: "/flags/bn.svg",
    acceptedAliases: ["Brunei", "Nation of Brunei, Abode of Peace"],
  },
  {
    id: "bg",
    alpha2Code: "BG",
    displayName: "Bulgaria",
    assetPath: "/flags/bg.svg",
    acceptedAliases: ["Bulgaria", "Republic of Bulgaria"],
  },
  {
    id: "bf",
    alpha2Code: "BF",
    displayName: "Burkina Faso",
    assetPath: "/flags/bf.svg",
    acceptedAliases: ["Burkina Faso"],
  },
  {
    id: "bi",
    alpha2Code: "BI",
    displayName: "Burundi",
    assetPath: "/flags/bi.svg",
    acceptedAliases: ["Burundi", "Republic of Burundi"],
  },
  {
    id: "kh",
    alpha2Code: "KH",
    displayName: "Cambodia",
    assetPath: "/flags/kh.svg",
    acceptedAliases: ["Cambodia", "Kingdom of Cambodia"],
  },
  {
    id: "cm",
    alpha2Code: "CM",
    displayName: "Cameroon",
    assetPath: "/flags/cm.svg",
    acceptedAliases: ["Cameroon", "Republic of Cameroon"],
  },
  {
    id: "ca",
    alpha2Code: "CA",
    displayName: "Canada",
    assetPath: "/flags/ca.svg",
    acceptedAliases: ["Canada"],
  },
  {
    id: "cv",
    alpha2Code: "CV",
    displayName: "Cape Verde",
    assetPath: "/flags/cv.svg",
    acceptedAliases: ["Cape Verde", "Republic of Cabo Verde"],
  },
  {
    id: "cf",
    alpha2Code: "CF",
    displayName: "Central African Republic",
    assetPath: "/flags/cf.svg",
    acceptedAliases: ["Central African Republic"],
  },
  {
    id: "td",
    alpha2Code: "TD",
    displayName: "Chad",
    assetPath: "/flags/td.svg",
    acceptedAliases: ["Chad", "Republic of Chad"],
  },
  {
    id: "cl",
    alpha2Code: "CL",
    displayName: "Chile",
    assetPath: "/flags/cl.svg",
    acceptedAliases: ["Chile", "Republic of Chile"],
  },
  {
    id: "cn",
    alpha2Code: "CN",
    displayName: "China",
    assetPath: "/flags/cn.svg",
    acceptedAliases: ["China", "People's Republic of China"],
  },
  {
    id: "co",
    alpha2Code: "CO",
    displayName: "Colombia",
    assetPath: "/flags/co.svg",
    acceptedAliases: ["Colombia", "Republic of Colombia"],
  },
  {
    id: "km",
    alpha2Code: "KM",
    displayName: "Comoros",
    assetPath: "/flags/km.svg",
    acceptedAliases: ["Comoros", "Union of the Comoros"],
  },
  {
    id: "cr",
    alpha2Code: "CR",
    displayName: "Costa Rica",
    assetPath: "/flags/cr.svg",
    acceptedAliases: ["Costa Rica", "Republic of Costa Rica"],
  },
  {
    id: "hr",
    alpha2Code: "HR",
    displayName: "Croatia",
    assetPath: "/flags/hr.svg",
    acceptedAliases: ["Croatia", "Republic of Croatia"],
  },
  {
    id: "cu",
    alpha2Code: "CU",
    displayName: "Cuba",
    assetPath: "/flags/cu.svg",
    acceptedAliases: ["Cuba", "Republic of Cuba"],
  },
  {
    id: "cy",
    alpha2Code: "CY",
    displayName: "Cyprus",
    assetPath: "/flags/cy.svg",
    acceptedAliases: ["Cyprus", "Republic of Cyprus"],
  },
  {
    id: "cz",
    alpha2Code: "CZ",
    displayName: "Czechia",
    assetPath: "/flags/cz.svg",
    acceptedAliases: ["Czechia", "Czech Republic"],
  },
  {
    id: "cd",
    alpha2Code: "CD",
    displayName: "DR Congo",
    assetPath: "/flags/cd.svg",
    acceptedAliases: ["DR Congo", "Democratic Republic of the Congo", "Congo Kinshasa"],
  },
  {
    id: "dk",
    alpha2Code: "DK",
    displayName: "Denmark",
    assetPath: "/flags/dk.svg",
    acceptedAliases: ["Denmark", "Kingdom of Denmark"],
  },
  {
    id: "dj",
    alpha2Code: "DJ",
    displayName: "Djibouti",
    assetPath: "/flags/dj.svg",
    acceptedAliases: ["Djibouti", "Republic of Djibouti"],
  },
  {
    id: "dm",
    alpha2Code: "DM",
    displayName: "Dominica",
    assetPath: "/flags/dm.svg",
    acceptedAliases: ["Dominica", "Commonwealth of Dominica"],
  },
  {
    id: "do",
    alpha2Code: "DO",
    displayName: "Dominican Republic",
    assetPath: "/flags/do.svg",
    acceptedAliases: ["Dominican Republic"],
  },
  {
    id: "ec",
    alpha2Code: "EC",
    displayName: "Ecuador",
    assetPath: "/flags/ec.svg",
    acceptedAliases: ["Ecuador", "Republic of Ecuador"],
  },
  {
    id: "eg",
    alpha2Code: "EG",
    displayName: "Egypt",
    assetPath: "/flags/eg.svg",
    acceptedAliases: ["Egypt", "Arab Republic of Egypt"],
  },
  {
    id: "sv",
    alpha2Code: "SV",
    displayName: "El Salvador",
    assetPath: "/flags/sv.svg",
    acceptedAliases: ["El Salvador", "Republic of El Salvador"],
  },
  {
    id: "gq",
    alpha2Code: "GQ",
    displayName: "Equatorial Guinea",
    assetPath: "/flags/gq.svg",
    acceptedAliases: ["Equatorial Guinea", "Republic of Equatorial Guinea"],
  },
  {
    id: "er",
    alpha2Code: "ER",
    displayName: "Eritrea",
    assetPath: "/flags/er.svg",
    acceptedAliases: ["Eritrea", "State of Eritrea"],
  },
  {
    id: "ee",
    alpha2Code: "EE",
    displayName: "Estonia",
    assetPath: "/flags/ee.svg",
    acceptedAliases: ["Estonia", "Republic of Estonia"],
  },
  {
    id: "sz",
    alpha2Code: "SZ",
    displayName: "Eswatini",
    assetPath: "/flags/sz.svg",
    acceptedAliases: ["Eswatini", "Kingdom of Eswatini", "Swaziland"],
  },
  {
    id: "et",
    alpha2Code: "ET",
    displayName: "Ethiopia",
    assetPath: "/flags/et.svg",
    acceptedAliases: ["Ethiopia", "Federal Democratic Republic of Ethiopia"],
  },
  {
    id: "fj",
    alpha2Code: "FJ",
    displayName: "Fiji",
    assetPath: "/flags/fj.svg",
    acceptedAliases: ["Fiji", "Republic of Fiji"],
  },
  {
    id: "fi",
    alpha2Code: "FI",
    displayName: "Finland",
    assetPath: "/flags/fi.svg",
    acceptedAliases: ["Finland", "Republic of Finland"],
  },
  {
    id: "fr",
    alpha2Code: "FR",
    displayName: "France",
    assetPath: "/flags/fr.svg",
    acceptedAliases: ["France", "French Republic"],
  },
  {
    id: "ga",
    alpha2Code: "GA",
    displayName: "Gabon",
    assetPath: "/flags/ga.svg",
    acceptedAliases: ["Gabon", "Gabonese Republic"],
  },
  {
    id: "gm",
    alpha2Code: "GM",
    displayName: "Gambia",
    assetPath: "/flags/gm.svg",
    acceptedAliases: ["Gambia", "Republic of the Gambia"],
  },
  {
    id: "ge",
    alpha2Code: "GE",
    displayName: "Georgia",
    assetPath: "/flags/ge.svg",
    acceptedAliases: ["Georgia"],
  },
  {
    id: "de",
    alpha2Code: "DE",
    displayName: "Germany",
    assetPath: "/flags/de.svg",
    acceptedAliases: ["Germany", "Federal Republic of Germany"],
  },
  {
    id: "gh",
    alpha2Code: "GH",
    displayName: "Ghana",
    assetPath: "/flags/gh.svg",
    acceptedAliases: ["Ghana", "Republic of Ghana"],
  },
  {
    id: "gr",
    alpha2Code: "GR",
    displayName: "Greece",
    assetPath: "/flags/gr.svg",
    acceptedAliases: ["Greece", "Hellenic Republic"],
  },
  {
    id: "gd",
    alpha2Code: "GD",
    displayName: "Grenada",
    assetPath: "/flags/gd.svg",
    acceptedAliases: ["Grenada"],
  },
  {
    id: "gt",
    alpha2Code: "GT",
    displayName: "Guatemala",
    assetPath: "/flags/gt.svg",
    acceptedAliases: ["Guatemala", "Republic of Guatemala"],
  },
  {
    id: "gn",
    alpha2Code: "GN",
    displayName: "Guinea",
    assetPath: "/flags/gn.svg",
    acceptedAliases: ["Guinea", "Republic of Guinea"],
  },
  {
    id: "gw",
    alpha2Code: "GW",
    displayName: "Guinea-Bissau",
    assetPath: "/flags/gw.svg",
    acceptedAliases: ["Guinea-Bissau", "Republic of Guinea-Bissau"],
  },
  {
    id: "gy",
    alpha2Code: "GY",
    displayName: "Guyana",
    assetPath: "/flags/gy.svg",
    acceptedAliases: ["Guyana", "Co-operative Republic of Guyana"],
  },
  {
    id: "ht",
    alpha2Code: "HT",
    displayName: "Haiti",
    assetPath: "/flags/ht.svg",
    acceptedAliases: ["Haiti", "Republic of Haiti"],
  },
  {
    id: "hn",
    alpha2Code: "HN",
    displayName: "Honduras",
    assetPath: "/flags/hn.svg",
    acceptedAliases: ["Honduras", "Republic of Honduras"],
  },
  {
    id: "hu",
    alpha2Code: "HU",
    displayName: "Hungary",
    assetPath: "/flags/hu.svg",
    acceptedAliases: ["Hungary"],
  },
  {
    id: "is",
    alpha2Code: "IS",
    displayName: "Iceland",
    assetPath: "/flags/is.svg",
    acceptedAliases: ["Iceland"],
  },
  {
    id: "in",
    alpha2Code: "IN",
    displayName: "India",
    assetPath: "/flags/in.svg",
    acceptedAliases: ["India", "Republic of India"],
  },
  {
    id: "id",
    alpha2Code: "ID",
    displayName: "Indonesia",
    assetPath: "/flags/id.svg",
    acceptedAliases: ["Indonesia", "Republic of Indonesia"],
  },
  {
    id: "ir",
    alpha2Code: "IR",
    displayName: "Iran",
    assetPath: "/flags/ir.svg",
    acceptedAliases: ["Iran", "Islamic Republic of Iran"],
  },
  {
    id: "iq",
    alpha2Code: "IQ",
    displayName: "Iraq",
    assetPath: "/flags/iq.svg",
    acceptedAliases: ["Iraq", "Republic of Iraq"],
  },
  {
    id: "ie",
    alpha2Code: "IE",
    displayName: "Ireland",
    assetPath: "/flags/ie.svg",
    acceptedAliases: ["Ireland", "Republic of Ireland"],
  },
  {
    id: "il",
    alpha2Code: "IL",
    displayName: "Israel",
    assetPath: "/flags/il.svg",
    acceptedAliases: ["Israel", "State of Israel"],
  },
  {
    id: "it",
    alpha2Code: "IT",
    displayName: "Italy",
    assetPath: "/flags/it.svg",
    acceptedAliases: ["Italy", "Italian Republic"],
  },
  {
    id: "ci",
    alpha2Code: "CI",
    displayName: "Ivory Coast",
    assetPath: "/flags/ci.svg",
    acceptedAliases: ["Ivory Coast", "Republic of Cote d'Ivoire", "Cote d'Ivoire", "Cote d Ivoire"],
  },
  {
    id: "jm",
    alpha2Code: "JM",
    displayName: "Jamaica",
    assetPath: "/flags/jm.svg",
    acceptedAliases: ["Jamaica"],
  },
  {
    id: "jp",
    alpha2Code: "JP",
    displayName: "Japan",
    assetPath: "/flags/jp.svg",
    acceptedAliases: ["Japan"],
  },
  {
    id: "jo",
    alpha2Code: "JO",
    displayName: "Jordan",
    assetPath: "/flags/jo.svg",
    acceptedAliases: ["Jordan", "Hashemite Kingdom of Jordan"],
  },
  {
    id: "kz",
    alpha2Code: "KZ",
    displayName: "Kazakhstan",
    assetPath: "/flags/kz.svg",
    acceptedAliases: ["Kazakhstan", "Republic of Kazakhstan"],
  },
  {
    id: "ke",
    alpha2Code: "KE",
    displayName: "Kenya",
    assetPath: "/flags/ke.svg",
    acceptedAliases: ["Kenya", "Republic of Kenya"],
  },
  {
    id: "ki",
    alpha2Code: "KI",
    displayName: "Kiribati",
    assetPath: "/flags/ki.svg",
    acceptedAliases: ["Kiribati", "Independent and Sovereign Republic of Kiribati"],
  },
  {
    id: "kw",
    alpha2Code: "KW",
    displayName: "Kuwait",
    assetPath: "/flags/kw.svg",
    acceptedAliases: ["Kuwait", "State of Kuwait"],
  },
  {
    id: "kg",
    alpha2Code: "KG",
    displayName: "Kyrgyzstan",
    assetPath: "/flags/kg.svg",
    acceptedAliases: ["Kyrgyzstan", "Kyrgyz Republic"],
  },
  {
    id: "la",
    alpha2Code: "LA",
    displayName: "Laos",
    assetPath: "/flags/la.svg",
    acceptedAliases: ["Laos", "Lao People's Democratic Republic"],
  },
  {
    id: "lv",
    alpha2Code: "LV",
    displayName: "Latvia",
    assetPath: "/flags/lv.svg",
    acceptedAliases: ["Latvia", "Republic of Latvia"],
  },
  {
    id: "lb",
    alpha2Code: "LB",
    displayName: "Lebanon",
    assetPath: "/flags/lb.svg",
    acceptedAliases: ["Lebanon", "Lebanese Republic"],
  },
  {
    id: "ls",
    alpha2Code: "LS",
    displayName: "Lesotho",
    assetPath: "/flags/ls.svg",
    acceptedAliases: ["Lesotho", "Kingdom of Lesotho"],
  },
  {
    id: "lr",
    alpha2Code: "LR",
    displayName: "Liberia",
    assetPath: "/flags/lr.svg",
    acceptedAliases: ["Liberia", "Republic of Liberia"],
  },
  {
    id: "ly",
    alpha2Code: "LY",
    displayName: "Libya",
    assetPath: "/flags/ly.svg",
    acceptedAliases: ["Libya", "State of Libya"],
  },
  {
    id: "li",
    alpha2Code: "LI",
    displayName: "Liechtenstein",
    assetPath: "/flags/li.svg",
    acceptedAliases: ["Liechtenstein", "Principality of Liechtenstein"],
  },
  {
    id: "lt",
    alpha2Code: "LT",
    displayName: "Lithuania",
    assetPath: "/flags/lt.svg",
    acceptedAliases: ["Lithuania", "Republic of Lithuania"],
  },
  {
    id: "lu",
    alpha2Code: "LU",
    displayName: "Luxembourg",
    assetPath: "/flags/lu.svg",
    acceptedAliases: ["Luxembourg", "Grand Duchy of Luxembourg"],
  },
  {
    id: "mg",
    alpha2Code: "MG",
    displayName: "Madagascar",
    assetPath: "/flags/mg.svg",
    acceptedAliases: ["Madagascar", "Republic of Madagascar"],
  },
  {
    id: "mw",
    alpha2Code: "MW",
    displayName: "Malawi",
    assetPath: "/flags/mw.svg",
    acceptedAliases: ["Malawi", "Republic of Malawi"],
  },
  {
    id: "my",
    alpha2Code: "MY",
    displayName: "Malaysia",
    assetPath: "/flags/my.svg",
    acceptedAliases: ["Malaysia"],
  },
  {
    id: "mv",
    alpha2Code: "MV",
    displayName: "Maldives",
    assetPath: "/flags/mv.svg",
    acceptedAliases: ["Maldives", "Republic of the Maldives"],
  },
  {
    id: "ml",
    alpha2Code: "ML",
    displayName: "Mali",
    assetPath: "/flags/ml.svg",
    acceptedAliases: ["Mali", "Republic of Mali"],
  },
  {
    id: "mt",
    alpha2Code: "MT",
    displayName: "Malta",
    assetPath: "/flags/mt.svg",
    acceptedAliases: ["Malta", "Republic of Malta"],
  },
  {
    id: "mh",
    alpha2Code: "MH",
    displayName: "Marshall Islands",
    assetPath: "/flags/mh.svg",
    acceptedAliases: ["Marshall Islands", "Republic of the Marshall Islands"],
  },
  {
    id: "mr",
    alpha2Code: "MR",
    displayName: "Mauritania",
    assetPath: "/flags/mr.svg",
    acceptedAliases: ["Mauritania", "Islamic Republic of Mauritania"],
  },
  {
    id: "mu",
    alpha2Code: "MU",
    displayName: "Mauritius",
    assetPath: "/flags/mu.svg",
    acceptedAliases: ["Mauritius", "Republic of Mauritius"],
  },
  {
    id: "mx",
    alpha2Code: "MX",
    displayName: "Mexico",
    assetPath: "/flags/mx.svg",
    acceptedAliases: ["Mexico", "United Mexican States"],
  },
  {
    id: "fm",
    alpha2Code: "FM",
    displayName: "Micronesia",
    assetPath: "/flags/fm.svg",
    acceptedAliases: ["Micronesia", "Federated States of Micronesia"],
  },
  {
    id: "md",
    alpha2Code: "MD",
    displayName: "Moldova",
    assetPath: "/flags/md.svg",
    acceptedAliases: ["Moldova", "Republic of Moldova"],
  },
  {
    id: "mc",
    alpha2Code: "MC",
    displayName: "Monaco",
    assetPath: "/flags/mc.svg",
    acceptedAliases: ["Monaco", "Principality of Monaco"],
  },
  {
    id: "mn",
    alpha2Code: "MN",
    displayName: "Mongolia",
    assetPath: "/flags/mn.svg",
    acceptedAliases: ["Mongolia"],
  },
  {
    id: "me",
    alpha2Code: "ME",
    displayName: "Montenegro",
    assetPath: "/flags/me.svg",
    acceptedAliases: ["Montenegro"],
  },
  {
    id: "ma",
    alpha2Code: "MA",
    displayName: "Morocco",
    assetPath: "/flags/ma.svg",
    acceptedAliases: ["Morocco", "Kingdom of Morocco"],
  },
  {
    id: "mz",
    alpha2Code: "MZ",
    displayName: "Mozambique",
    assetPath: "/flags/mz.svg",
    acceptedAliases: ["Mozambique", "Republic of Mozambique"],
  },
  {
    id: "mm",
    alpha2Code: "MM",
    displayName: "Myanmar",
    assetPath: "/flags/mm.svg",
    acceptedAliases: ["Myanmar", "Republic of the Union of Myanmar", "Burma"],
  },
  {
    id: "na",
    alpha2Code: "NA",
    displayName: "Namibia",
    assetPath: "/flags/na.svg",
    acceptedAliases: ["Namibia", "Republic of Namibia"],
  },
  {
    id: "nr",
    alpha2Code: "NR",
    displayName: "Nauru",
    assetPath: "/flags/nr.svg",
    acceptedAliases: ["Nauru", "Republic of Nauru"],
  },
  {
    id: "np",
    alpha2Code: "NP",
    displayName: "Nepal",
    assetPath: "/flags/np.svg",
    acceptedAliases: ["Nepal", "Federal Democratic Republic of Nepal"],
  },
  {
    id: "nl",
    alpha2Code: "NL",
    displayName: "Netherlands",
    assetPath: "/flags/nl.svg",
    acceptedAliases: ["Netherlands", "Kingdom of the Netherlands"],
  },
  {
    id: "nz",
    alpha2Code: "NZ",
    displayName: "New Zealand",
    assetPath: "/flags/nz.svg",
    acceptedAliases: ["New Zealand"],
  },
  {
    id: "ni",
    alpha2Code: "NI",
    displayName: "Nicaragua",
    assetPath: "/flags/ni.svg",
    acceptedAliases: ["Nicaragua", "Republic of Nicaragua"],
  },
  {
    id: "ne",
    alpha2Code: "NE",
    displayName: "Niger",
    assetPath: "/flags/ne.svg",
    acceptedAliases: ["Niger", "Republic of Niger"],
  },
  {
    id: "ng",
    alpha2Code: "NG",
    displayName: "Nigeria",
    assetPath: "/flags/ng.svg",
    acceptedAliases: ["Nigeria", "Federal Republic of Nigeria"],
  },
  {
    id: "kp",
    alpha2Code: "KP",
    displayName: "North Korea",
    assetPath: "/flags/kp.svg",
    acceptedAliases: ["North Korea", "Democratic People's Republic of Korea"],
  },
  {
    id: "mk",
    alpha2Code: "MK",
    displayName: "North Macedonia",
    assetPath: "/flags/mk.svg",
    acceptedAliases: ["North Macedonia", "Republic of North Macedonia", "Macedonia"],
  },
  {
    id: "no",
    alpha2Code: "NO",
    displayName: "Norway",
    assetPath: "/flags/no.svg",
    acceptedAliases: ["Norway", "Kingdom of Norway"],
  },
  {
    id: "om",
    alpha2Code: "OM",
    displayName: "Oman",
    assetPath: "/flags/om.svg",
    acceptedAliases: ["Oman", "Sultanate of Oman"],
  },
  {
    id: "pk",
    alpha2Code: "PK",
    displayName: "Pakistan",
    assetPath: "/flags/pk.svg",
    acceptedAliases: ["Pakistan", "Islamic Republic of Pakistan"],
  },
  {
    id: "pw",
    alpha2Code: "PW",
    displayName: "Palau",
    assetPath: "/flags/pw.svg",
    acceptedAliases: ["Palau", "Republic of Palau"],
  },
  {
    id: "pa",
    alpha2Code: "PA",
    displayName: "Panama",
    assetPath: "/flags/pa.svg",
    acceptedAliases: ["Panama", "Republic of Panama"],
  },
  {
    id: "pg",
    alpha2Code: "PG",
    displayName: "Papua New Guinea",
    assetPath: "/flags/pg.svg",
    acceptedAliases: ["Papua New Guinea", "Independent State of Papua New Guinea"],
  },
  {
    id: "py",
    alpha2Code: "PY",
    displayName: "Paraguay",
    assetPath: "/flags/py.svg",
    acceptedAliases: ["Paraguay", "Republic of Paraguay"],
  },
  {
    id: "pe",
    alpha2Code: "PE",
    displayName: "Peru",
    assetPath: "/flags/pe.svg",
    acceptedAliases: ["Peru", "Republic of Peru"],
  },
  {
    id: "ph",
    alpha2Code: "PH",
    displayName: "Philippines",
    assetPath: "/flags/ph.svg",
    acceptedAliases: ["Philippines", "Republic of the Philippines"],
  },
  {
    id: "pl",
    alpha2Code: "PL",
    displayName: "Poland",
    assetPath: "/flags/pl.svg",
    acceptedAliases: ["Poland", "Republic of Poland"],
  },
  {
    id: "pt",
    alpha2Code: "PT",
    displayName: "Portugal",
    assetPath: "/flags/pt.svg",
    acceptedAliases: ["Portugal", "Portuguese Republic"],
  },
  {
    id: "qa",
    alpha2Code: "QA",
    displayName: "Qatar",
    assetPath: "/flags/qa.svg",
    acceptedAliases: ["Qatar", "State of Qatar"],
  },
  {
    id: "cg",
    alpha2Code: "CG",
    displayName: "Republic of the Congo",
    assetPath: "/flags/cg.svg",
    acceptedAliases: ["Republic of the Congo", "Congo Brazzaville"],
  },
  {
    id: "ro",
    alpha2Code: "RO",
    displayName: "Romania",
    assetPath: "/flags/ro.svg",
    acceptedAliases: ["Romania"],
  },
  {
    id: "ru",
    alpha2Code: "RU",
    displayName: "Russia",
    assetPath: "/flags/ru.svg",
    acceptedAliases: ["Russia", "Russian Federation"],
  },
  {
    id: "rw",
    alpha2Code: "RW",
    displayName: "Rwanda",
    assetPath: "/flags/rw.svg",
    acceptedAliases: ["Rwanda", "Republic of Rwanda"],
  },
  {
    id: "kn",
    alpha2Code: "KN",
    displayName: "Saint Kitts and Nevis",
    assetPath: "/flags/kn.svg",
    acceptedAliases: ["Saint Kitts and Nevis", "Federation of Saint Christopher and Nevis"],
  },
  {
    id: "lc",
    alpha2Code: "LC",
    displayName: "Saint Lucia",
    assetPath: "/flags/lc.svg",
    acceptedAliases: ["Saint Lucia"],
  },
  {
    id: "vc",
    alpha2Code: "VC",
    displayName: "Saint Vincent and the Grenadines",
    assetPath: "/flags/vc.svg",
    acceptedAliases: ["Saint Vincent and the Grenadines"],
  },
  {
    id: "ws",
    alpha2Code: "WS",
    displayName: "Samoa",
    assetPath: "/flags/ws.svg",
    acceptedAliases: ["Samoa", "Independent State of Samoa"],
  },
  {
    id: "sm",
    alpha2Code: "SM",
    displayName: "San Marino",
    assetPath: "/flags/sm.svg",
    acceptedAliases: ["San Marino", "Republic of San Marino"],
  },
  {
    id: "st",
    alpha2Code: "ST",
    displayName: "Sao Tome and Principe",
    assetPath: "/flags/st.svg",
    acceptedAliases: ["Sao Tome and Principe", "Democratic Republic of Sao Tome and Principe", "Sao Tome"],
  },
  {
    id: "sa",
    alpha2Code: "SA",
    displayName: "Saudi Arabia",
    assetPath: "/flags/sa.svg",
    acceptedAliases: ["Saudi Arabia", "Kingdom of Saudi Arabia"],
  },
  {
    id: "sn",
    alpha2Code: "SN",
    displayName: "Senegal",
    assetPath: "/flags/sn.svg",
    acceptedAliases: ["Senegal", "Republic of Senegal"],
  },
  {
    id: "rs",
    alpha2Code: "RS",
    displayName: "Serbia",
    assetPath: "/flags/rs.svg",
    acceptedAliases: ["Serbia", "Republic of Serbia"],
  },
  {
    id: "sc",
    alpha2Code: "SC",
    displayName: "Seychelles",
    assetPath: "/flags/sc.svg",
    acceptedAliases: ["Seychelles", "Republic of Seychelles"],
  },
  {
    id: "sl",
    alpha2Code: "SL",
    displayName: "Sierra Leone",
    assetPath: "/flags/sl.svg",
    acceptedAliases: ["Sierra Leone", "Republic of Sierra Leone"],
  },
  {
    id: "sg",
    alpha2Code: "SG",
    displayName: "Singapore",
    assetPath: "/flags/sg.svg",
    acceptedAliases: ["Singapore", "Republic of Singapore"],
  },
  {
    id: "sk",
    alpha2Code: "SK",
    displayName: "Slovakia",
    assetPath: "/flags/sk.svg",
    acceptedAliases: ["Slovakia", "Slovak Republic"],
  },
  {
    id: "si",
    alpha2Code: "SI",
    displayName: "Slovenia",
    assetPath: "/flags/si.svg",
    acceptedAliases: ["Slovenia", "Republic of Slovenia"],
  },
  {
    id: "sb",
    alpha2Code: "SB",
    displayName: "Solomon Islands",
    assetPath: "/flags/sb.svg",
    acceptedAliases: ["Solomon Islands"],
  },
  {
    id: "so",
    alpha2Code: "SO",
    displayName: "Somalia",
    assetPath: "/flags/so.svg",
    acceptedAliases: ["Somalia", "Federal Republic of Somalia"],
  },
  {
    id: "za",
    alpha2Code: "ZA",
    displayName: "South Africa",
    assetPath: "/flags/za.svg",
    acceptedAliases: ["South Africa", "Republic of South Africa"],
  },
  {
    id: "kr",
    alpha2Code: "KR",
    displayName: "South Korea",
    assetPath: "/flags/kr.svg",
    acceptedAliases: ["South Korea", "Republic of Korea"],
  },
  {
    id: "ss",
    alpha2Code: "SS",
    displayName: "South Sudan",
    assetPath: "/flags/ss.svg",
    acceptedAliases: ["South Sudan", "Republic of South Sudan"],
  },
  {
    id: "es",
    alpha2Code: "ES",
    displayName: "Spain",
    assetPath: "/flags/es.svg",
    acceptedAliases: ["Spain", "Kingdom of Spain"],
  },
  {
    id: "lk",
    alpha2Code: "LK",
    displayName: "Sri Lanka",
    assetPath: "/flags/lk.svg",
    acceptedAliases: ["Sri Lanka", "Democratic Socialist Republic of Sri Lanka"],
  },
  {
    id: "sd",
    alpha2Code: "SD",
    displayName: "Sudan",
    assetPath: "/flags/sd.svg",
    acceptedAliases: ["Sudan", "Republic of the Sudan"],
  },
  {
    id: "sr",
    alpha2Code: "SR",
    displayName: "Suriname",
    assetPath: "/flags/sr.svg",
    acceptedAliases: ["Suriname", "Republic of Suriname"],
  },
  {
    id: "se",
    alpha2Code: "SE",
    displayName: "Sweden",
    assetPath: "/flags/se.svg",
    acceptedAliases: ["Sweden", "Kingdom of Sweden"],
  },
  {
    id: "ch",
    alpha2Code: "CH",
    displayName: "Switzerland",
    assetPath: "/flags/ch.svg",
    acceptedAliases: ["Switzerland", "Swiss Confederation"],
  },
  {
    id: "sy",
    alpha2Code: "SY",
    displayName: "Syria",
    assetPath: "/flags/sy.svg",
    acceptedAliases: ["Syria", "Syrian Arab Republic"],
  },
  {
    id: "tj",
    alpha2Code: "TJ",
    displayName: "Tajikistan",
    assetPath: "/flags/tj.svg",
    acceptedAliases: ["Tajikistan", "Republic of Tajikistan"],
  },
  {
    id: "tz",
    alpha2Code: "TZ",
    displayName: "Tanzania",
    assetPath: "/flags/tz.svg",
    acceptedAliases: ["Tanzania", "United Republic of Tanzania"],
  },
  {
    id: "th",
    alpha2Code: "TH",
    displayName: "Thailand",
    assetPath: "/flags/th.svg",
    acceptedAliases: ["Thailand", "Kingdom of Thailand"],
  },
  {
    id: "tl",
    alpha2Code: "TL",
    displayName: "Timor-Leste",
    assetPath: "/flags/tl.svg",
    acceptedAliases: ["Timor-Leste", "Democratic Republic of Timor-Leste", "East Timor"],
  },
  {
    id: "tg",
    alpha2Code: "TG",
    displayName: "Togo",
    assetPath: "/flags/tg.svg",
    acceptedAliases: ["Togo", "Togolese Republic"],
  },
  {
    id: "to",
    alpha2Code: "TO",
    displayName: "Tonga",
    assetPath: "/flags/to.svg",
    acceptedAliases: ["Tonga", "Kingdom of Tonga"],
  },
  {
    id: "tt",
    alpha2Code: "TT",
    displayName: "Trinidad and Tobago",
    assetPath: "/flags/tt.svg",
    acceptedAliases: ["Trinidad and Tobago", "Republic of Trinidad and Tobago"],
  },
  {
    id: "tn",
    alpha2Code: "TN",
    displayName: "Tunisia",
    assetPath: "/flags/tn.svg",
    acceptedAliases: ["Tunisia", "Tunisian Republic"],
  },
  {
    id: "tr",
    alpha2Code: "TR",
    displayName: "Turkey",
    assetPath: "/flags/tr.svg",
    acceptedAliases: ["Turkey", "Republic of Turkey"],
  },
  {
    id: "tm",
    alpha2Code: "TM",
    displayName: "Turkmenistan",
    assetPath: "/flags/tm.svg",
    acceptedAliases: ["Turkmenistan"],
  },
  {
    id: "tv",
    alpha2Code: "TV",
    displayName: "Tuvalu",
    assetPath: "/flags/tv.svg",
    acceptedAliases: ["Tuvalu"],
  },
  {
    id: "ug",
    alpha2Code: "UG",
    displayName: "Uganda",
    assetPath: "/flags/ug.svg",
    acceptedAliases: ["Uganda", "Republic of Uganda"],
  },
  {
    id: "ua",
    alpha2Code: "UA",
    displayName: "Ukraine",
    assetPath: "/flags/ua.svg",
    acceptedAliases: ["Ukraine"],
  },
  {
    id: "ae",
    alpha2Code: "AE",
    displayName: "United Arab Emirates",
    assetPath: "/flags/ae.svg",
    acceptedAliases: ["United Arab Emirates", "UAE"],
  },
  {
    id: "gb",
    alpha2Code: "GB",
    displayName: "United Kingdom",
    assetPath: "/flags/gb.svg",
    acceptedAliases: ["United Kingdom", "United Kingdom of Great Britain and Northern Ireland", "UK", "Great Britain", "Britain"],
  },
  {
    id: "us",
    alpha2Code: "US",
    displayName: "United States",
    assetPath: "/flags/us.svg",
    acceptedAliases: ["United States", "United States of America", "USA", "America"],
  },
  {
    id: "uy",
    alpha2Code: "UY",
    displayName: "Uruguay",
    assetPath: "/flags/uy.svg",
    acceptedAliases: ["Uruguay", "Oriental Republic of Uruguay"],
  },
  {
    id: "uz",
    alpha2Code: "UZ",
    displayName: "Uzbekistan",
    assetPath: "/flags/uz.svg",
    acceptedAliases: ["Uzbekistan", "Republic of Uzbekistan"],
  },
  {
    id: "vu",
    alpha2Code: "VU",
    displayName: "Vanuatu",
    assetPath: "/flags/vu.svg",
    acceptedAliases: ["Vanuatu", "Republic of Vanuatu"],
  },
  {
    id: "va",
    alpha2Code: "VA",
    displayName: "Vatican City",
    assetPath: "/flags/va.svg",
    acceptedAliases: ["Vatican City", "Vatican City State", "Vatican"],
  },
  {
    id: "ve",
    alpha2Code: "VE",
    displayName: "Venezuela",
    assetPath: "/flags/ve.svg",
    acceptedAliases: ["Venezuela", "Bolivarian Republic of Venezuela"],
  },
  {
    id: "vn",
    alpha2Code: "VN",
    displayName: "Vietnam",
    assetPath: "/flags/vn.svg",
    acceptedAliases: ["Vietnam", "Socialist Republic of Vietnam"],
  },
  {
    id: "ye",
    alpha2Code: "YE",
    displayName: "Yemen",
    assetPath: "/flags/ye.svg",
    acceptedAliases: ["Yemen", "Republic of Yemen"],
  },
  {
    id: "zm",
    alpha2Code: "ZM",
    displayName: "Zambia",
    assetPath: "/flags/zm.svg",
    acceptedAliases: ["Zambia", "Republic of Zambia"],
  },
  {
    id: "zw",
    alpha2Code: "ZW",
    displayName: "Zimbabwe",
    assetPath: "/flags/zw.svg",
    acceptedAliases: ["Zimbabwe", "Republic of Zimbabwe"],
  },
];

export const FLAG_COUNTRY_COUNT = FLAG_COUNTRIES.length;
